# Generated by Django 4.1.1 on 2022-09-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryID', models.IntegerField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.IntegerField(primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelId', models.IntegerField(primary_key=True, serialize=False)),
                ('hotelName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads')),
                ('stars', models.IntegerField(choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*'), (5, '5*')])),
                ('hotelCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
                ('hotelLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location')),
            ],
        ),
    ]
