# Generated by Django 4.1.1 on 2022-09-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='countryID',
            new_name='countryId',
        ),
    ]
