# Generated by Django 4.1.1 on 2022-09-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_country_countryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationId',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
