# Generated by Django 4.1.1 on 2022-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_name_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hotel',
            field=models.CharField(max_length=20),
        ),
    ]
