# Generated by Django 4.1.1 on 2022-09-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
