# Generated by Django 4.1.1 on 2022-09-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collectionId', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('collectionName', models.CharField(max_length=100)),
            ],
        ),
    ]
