# Generated by Django 4.1.1 on 2022-09-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='collection',
            field=models.ForeignKey(default='hc', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.collection'),
        ),
    ]
