# Generated by Django 4.1.1 on 2022-09-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_hotel_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='collection',
        ),
        migrations.AddField(
            model_name='hotel',
            name='collection',
            field=models.ManyToManyField(to='app.collection'),
        ),
    ]
