# Generated by Django 4.1.1 on 2022-09-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_hotel_collection_hotel_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collectionPhoto',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
